version: "1.0"
name: ouvidoria-app

services:
  - name: api
    github:
      repo: Lucas0304200/ouvidoria
      branch: main

    # instala dependências do backend
    build:
      command: pip install -r backend/requirements.txt

    # executa a aplicação Flask
    run:
      command: python backend/back_end.py

    envs:
      DB_HOST:     ${db.HOSTNAME}
      DB_PORT:     ${db.PORT}
      DB_USER:     ${db.USERNAME}
      DB_PASSWORD: ${db.PASSWORD}
      DB_NAME:     ${db.DATABASE}
      PORT:        ${_self.PRIVATE_PORT}

    health_check:
      http_path:           /health
      initial_delay_seconds: 10
      period_seconds:        30
      timeout_seconds:       5
      success_threshold:     1
      failure_threshold:     3

  - name: frontend
    github:
      repo: seu-usuario/ouvidoria
      branch: main

    # sem build
    build:
      command: echo "No build required"

    # onde estão os arquivos estáticos
    static:
      output_dir: frontend/public

    routes:
      - path: /

    cors:
      allow_origins:
        - regex: .*
      allow_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allow_headers:
        - Content-Type
        - Authorization
      expose_headers:
        - Content-Length
      max_age: 86400
