[phases.setup]
# gcc, mariadb e Python 3.11 + pip do conjunto python311Packages
nixPkgs = [
  "gcc",
  "mariadb",
  "python311",
  "python311Packages.pip"
]

[phases.install]
cmds = [
  "pip install -r backend/requirements.txt"
]

[phases.start]
cmd = "gunicorn back_end:app"
